#DataBase
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Trucks
    username: dmitry
    password: dmitry
  jpa:
    hibernate:
      ddl-auto: validate

#Flyway
flyway:
  enabled: true
  locations: classpath:db/migration
  check-location: true
  baseline-on-migrate: true