server:
  port: 9090

#DataBase
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Cargo_Managament_System_DB
    username: Dmitry
    password: Dmitry
  jpa:
    hibernate:
      ddl-auto: validate

#Flyway
flyway:
  enabled: true
  locations: classpath:db/migration
  check-location: true
  baseline-on-migrate: true

#JWT
secret.key: dc6589483a672de25ff765172494d42e138cd8a5
auth.header.name: Token
token.expiration.time: 3